import Head from 'next/head'
import Hero from "@/components/Hero";
import homeImg from "../public/img/hero/hero.jpg"
import About from "@/components/Home/About";
import Projects from "@/components/Home/Projects";
import Advantages from "@/components/Home/Advantages";
import Services from "@/components/Home/Services";
import Partners from "@/components/Home/Partners";
import Mail from "@/components/Mail";

export default function Home({lang}) {
    return (
        <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next index"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
        <>
        <Hero
            withIcon={true}
            btnText="our projects"
            text="hero.home.title"
            desc="hero.home.description"
            logoBg="logo"
            bgImg={homeImg}
        />
            <About/>
            <Projects/>
            <Advantages/>
            <Services/>
            <Partners/>
            <Mail bgColor={'var(--section-bg-cream)'}/>
        </>

    </>
    )
}